spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookdb?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: admin
    password: admin
  #(create, create-drop, update)
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  liquibase:
    enabled: true
    drop-first: true
    change-log: classpath:db.changelog/baseline-changelog.xml
    default-schema: bookdb

